server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://devicecare_admin:admin124@cluster0.stssdaq.mongodb.net/auth_db?retryWrites=true&w=majority&appName=Cluster0
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_PRIVATE_DOMAIN:localhost}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:device-care-360.railway.internal}:8761/eureka/

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics