server:
  port: ${PORT:8081}

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://devicecare_admin:admin1234@cluster0.sfssdaq.mongodb.net/auth_db?retryWrites=true&w=majority&appName=Cluster0}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${RAILWAY_PRIVATE_DOMAIN:${HOSTNAME:localhost}}
    instance-id: ${HOSTNAME:auth-service}:${spring.application.name}:${server.port}
    non-secure-port: ${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_HOST:device-care-360.railway.internal}:8761/eureka/

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics