server:
  port: 8091

spring:
  application:
    name: admin-service
  data:
    mongodb:
      uri: mongodb+srv://devicecare_admin:admin1234@cluster0.sfssdaq.mongodb.net/admin_db?retryWrites=true&w=majority&appName=Cluster0

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
